In [ ]:
import torch
from torch import nn
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
import numpy as np

In [ ]:
W = np.array([0.3, 1.2])
b = 0.7

W, b

(array([0.3, 1.2]), 0.7)

In [ ]:
import torch
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# Tensor với giá trị ngẫu nhiên từ phân phối chuẩn
x_rand = torch.randn(2, 3)

# Tensor với tất cả phần tử bằng 1
x_ones = torch.ones(2, 3)

# Tensor với tất cả phần tử bằng 0
x_zeros = torch.zeros(2, 3)

x_data, x_rand, x_ones, x_zeros

(tensor([[1, 2],
         [3, 4]]),
 tensor([[-1.6668,  0.2100,  1.4686],
         [-1.4920, -1.9278,  0.1607]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
print(x_data.shape, x_data. dtype, x_data. device)

torch.Size([2, 2]) torch.int64 cpu


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_reshaped = x.view(3, 2)

y = torch.tensor([[1, 2, 3], [4, 5, 6]])
z = x + y

x, x_reshaped, z

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 2,  4,  6],
         [ 8, 10, 12]]))

In [ ]:
# Check if CUDA is available
if torch.cuda.is_available():
    # If CUDA is available, move the tensor to the GPU
    x_gpu = x.to('cuda')
    # Check if the tensor is on the GPU
    print(x_gpu.is_cuda)
else:
    # If CUDA is not available, print a message
    print("CUDA is not available. The tensor will remain on the CPU.")
    # Assign x to x_gpu to avoid NameError in the next line
    x_gpu = x

# Now x_gpu is defined regardless of CUDA availability
x_gpu.is_cuda

True


True